### ISSUE TITLE
any other place to download the wheel file

### ISSUE THREAD

**Issue by shyandsy** [ziyadkadekara/Installing-PyOpenGL-windows#1]
the webpage is missiong on this url
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl

**Comment by ziyadkadekara** [comment]
can you share what you see when you click the link. if it is showing  [Archived: Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/)

then scroll down and reach letter P (they are listed in alphabetic order


Thank you
